routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });

// Route d'authentification
Auth::routes();

// Page de Profil de l'utilisateur
Route::get('/home', 'HomeController@index')->name('home');

// Page d'acceuil
Route::get('/', 'internauteController@accueil')->name('accueil');

// Publications
Route::get('/article/{id}/detail', 'internauteController@view_article')->name('view_article');
Route::get('/articles', 'internauteController@list_articles')->name('list_articles');

// Interviews
Route::get('/interview/{id}/detail', 'internauteController@view_interview')->name('view_interview');
Route::get('/interview', 'internauteController@list_interview')->name('list_interview');

// Search
Route::get('/search', 'internauteController@search')->name('search');

// Contact
Route::get('/contact', 'internauteController@contact')->name('contact');

// Route dédiée au administrateurs connu sous le nom de membre (@membre @endmembre)

Route::middleware('membre')->group(function () {
	Route::group(['prefix' => 'admin'], function () {
	    Route::resource ('interviews', 'InterviewController', [
	        //'except' => 'show'
	    ]);
	    Route::resource('publications', 'publicationController');
	    Route::resource('flash', 'FlashController');
	    Route::resource('auteurs', 'AuteurController');
	    Route::resource('news', 'newsletterController');
	    // Envoie de mail à plusieurs
		Route::post('/all', 'newsletterController@all')->name('all');
		// Liste des messages envoyés au abonnés
		Route::get('/list_messages', 'newsletterController@list_messages')->name('list_messages');
	    // Contactez l'équipe
	    Route::resource('contact', 'ContactController');
	    // Commentaire des publications
	    //- Route::resource('commentpub', 'CommentPubController');
	    // Commentaire des interviews
	    //- Route::resource('commentint', 'CommentIntController');
    });
});


Route::middleware('auth')->group(function () {
	Route::group(['prefix' => 'admin'], function () {
	    // Commentaire des publications
	    Route::resource('commentpub', 'CommentPubController');
	    // Commentaire des interviews
	    Route::resource('commentint', 'CommentIntController');
    });
});

app/Models/Flash.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Flash extends Model
{
    protected $fillable = ['flashinfo'];
}

app/Http/Controllers/FlashController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Flash;

class FlashController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $flash = Flash::OrderBy('id','desc')->get();
        // dd($flash);
        return view('administration.Flash.index',compact('flash'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('administration.Flash.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request,[
           'flashinfo'=>'Required',
        ]); 

        Flash::create([
        'flashinfo'=>$request->flashinfo
        ]);
        Session()->flash('create', 'Le Flash info à été Ajouté avec success !'); 
        return redirect()->route('flash.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $flash=Flash::findOrFail($id);
        return view('administration.Flash.show',compact('flash'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $flash=Flash::findOrFail($id);
        return view('administration.Flash.edit',compact('flash'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request,[
           'flashinfo'=>'Required',
        ]); 

        $flash=Flash::findOrFail($id);
        $flash->update([
        'flashinfo'=>$request->flashinfo
        ]);
        Session()->flash('update', 'Le Flash info à été Ajouté avec success !'); 
        return redirect()->route('flash.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Flash::destroy($id);
        Session()->flash("delete", "Le flashinfo à bien été supprimé avec success !");  
        return redirect()->route('flash.index');
    }
}

resources/views/administration/Flash/create.blade.php
@extends('layouts.sidebar-profil') @section('content')



    <!--maincontent-->
        <div class="mainWrap navslide">
            <div class="ui equal width left aligned padded grid stackable">
                <!--Site Content-->
                <!--Site Content-->
            
                        <div class="row">
                          
                            <!--  -->
                            <!--  -->

                            <div class="ten wide column">
                                        <div class="ui segments">
                                    <div class="ui segment">
                                        <h5 class="ui header">
                                            Ajouter une info
                                        </h5>
                                        <a href="{{route('flash.index')}}">
                                            <button class="ui lightbrownli  button">Voir la liste</button>
                                        </a>
                                    </div>
                                    <form class="ui form segment form3" action="{{route('flash.store')}}" method="POST">
                                        {{csrf_field()}}
                                            @csrf
                                        <div class="field">
                                            <label>contenu du flash info</label>
                                            <div class="field">
                                                <!-- <input placeholder="contenu" name="flashinfo" type="text"> -->
                                                <textarea  name="flashinfo" id="" cols="30" rows="5"></textarea>
                                            </div>
                                        <button type="submit" class="ui blue submit button">Enregistrer</button>
                                    </form>
                                </div>
                            </div>

                            <!--  -->

                        </div>
            </div>
        </div>



@endsection

resources/views/administration/Flash/edit.blade.php
@extends('layouts.sidebar-profil') @section('content')



    <!--maincontent-->
        <div class="mainWrap navslide">
            <div class="ui equal width left aligned padded grid stackable">
                <!--Site Content-->
                <!--Site Content-->
            
                        <div class="row">
                          
                            <!--  -->
                            <!--  -->

                            <div class="ten wide column">
                                        <div class="ui segments">
                                    <div class="ui segment">
                                        <h5 class="ui header">
                                            Mettre à jour cette info
                                        </h5>
                                        <a href="{{route('flash.index')}}">
                                            <button class="ui lightbrownli  button">Voir la liste</button>
                                        </a>
                                    </div>
                                    <form class="ui form segment form3" action="{{route('flash.update', $flash)}}" method="POST">
                                          {{csrf_field()}}
                                        {{method_field('PUT')}}
                                        <div class="field">
                                            <label>contenu du flash info</label>
                                            <div class="field">
                                                <!-- <input placeholder="contenu" name="flashinfo" type="text"> -->
                                                <textarea  name="flashinfo" id="" cols="30" rows="5">{{$flash->flashinfo}}</textarea>
                                            </div>
                                        <button type="submit" class="ui blue submit button">Mettre à jour</button>
                                    </form>
                                </div>
                            </div>

                            <!--  -->

                        </div>
            </div>
        </div>



@endsection

resources/views/administration/Flash/index.blade.php
@extends('layouts.sidebar-profil') @section('content')

<br>


    <!--maincontent-->
        <div class="mainWrap navslide">
            <div class="ui equal width left aligned padded grid stackable">
                <!--Site Content-->
                <!--Site Content-->
            
                        <div class="row">
                            <div class="sixteen wide column">
                                <div class="ui segments">
                                    <div class="ui segment">
                                        <h5 class="ui header">
                                            Liste des infos 
                                        </h5>
                                        <a href="{{route('flash.create')}}">
                                            <button class="ui lightbrownli  button">Ajouter une nouvelle info</button>
                                        </a>
                                        @if(session()->has('create'))
                                            <div class="ui icon message inverted greenli">
                                                <i class="alarm icon"></i>
                                                <div class="content">
                                                    <div class="header">
                                                        {{ session()->get('create') }}
                                                    </div>
                                                    <!-- <p>{{ session()->get('create') }}</p> -->
                                                </div>
                                            </div>
                                        @endif 

                                         @if(session()->has('delete'))
                                            <div class="ui icon message inverted redli">
                                                <i class="alarm icon"></i>
                                                <div class="content">
                                                    <div class="header">
                                                        {{ session()->get('delete') }}
                                                    </div>
                                                    <!-- <p>{{ session()->get('delete') }}</p> -->
                                                </div>
                                            </div>
                                        @endif 

                                        @if(session()->has('update'))
                                            <div class="ui icon message inverted greenli">
                                                <i class="alarm icon"></i>
                                                <div class="content">
                                                    <div class="header">
                                                        {{ session()->get('update') }}
                                                    </div>
                                                    <!-- <p>{{ session()->get('update') }}</p> -->
                                                </div>
                                            </div>
                                        @endif


                                    </div>
                                    <div class="ui segment">
                                        <table id="data_table" class="ui compact selectable striped celled table tablet stackable" cellspacing="0" width="100%">
                                            <thead>
                                                <tr>
                                                    <th>Description</th>
                                                    <th>Date de publication</th>
                                                    <th>Modifier</th>
                                                    <th>Supprimer</th>
                                                </tr>
                                            </thead>

                                            <tbody>
                                                @foreach($flash as $Pub)
                                                <tr>
                                                    <td>{{$Pub->flashinfo}}</td>
                                                    <td>
                                                        {{date('d-m-Y', strtotime($Pub->created_at)) }}
                                                    </td>
                                                    <td> 
                                                        <a href="{{route('flash.edit',$Pub->id)}}">
                                                            <button class="ui brown button">
                                                                <i class="pencil alternate icon ui dark"></i>
                                                            </button>
                                                        </a>
                                                    </td>
                                                    <td>
                                                        <form action = "{{ route('flash.destroy',$Pub) }}"
                                                            method = "POST"
                                                            onsubmit = "return confirm('Êtes vous sûre ?')"; >
                                                            {{ csrf_field() }}
                                                            {{ method_field('DELETE') }}
                                                            <button class="ui red button" type="submit">
                                                                <i class="close icon ui dark"></i>
                                                            </button>
                                                        </form>
                                                    </td>
                                                </tr>
                                                @endforeach
                                                
                                            </tbody>
                                        </table>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
        </div>
        <!--maincontent-->



@endsection