routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });

// Route d'authentification
Auth::routes();

// Page de Profil de l'utilisateur
Route::get('/home', 'HomeController@index')->name('home');

// Page d'acceuil
Route::get('/', 'internauteController@accueil')->name('accueil');

// Publications
Route::get('/article/{id}/detail', 'internauteController@view_article')->name('view_article');
Route::get('/articles', 'internauteController@list_articles')->name('list_articles');

// Interviews
Route::get('/interview/{id}/detail', 'internauteController@view_interview')->name('view_interview');
Route::get('/interview', 'internauteController@list_interview')->name('list_interview');

// Search
Route::get('/search', 'internauteController@search')->name('search');

// Contact
Route::get('/contact', 'internauteController@contact')->name('contact');

// Route dédiée au administrateurs connu sous le nom de membre (@membre @endmembre)

Route::middleware('membre')->group(function () {
	Route::group(['prefix' => 'admin'], function () {
	    Route::resource ('interviews', 'InterviewController', [
	        //'except' => 'show'
	    ]);
	    Route::resource('publications', 'publicationController');
	    Route::resource('flash', 'FlashController');
	    Route::resource('auteurs', 'AuteurController');
	    Route::resource('news', 'newsletterController');
	    // Envoie de mail à plusieurs
		Route::post('/all', 'newsletterController@all')->name('all');
		// Liste des messages envoyés au abonnés
		Route::get('/list_messages', 'newsletterController@list_messages')->name('list_messages');
	    // Contactez l'équipe
	    Route::resource('contact', 'ContactController');
	    // Commentaire des publications
	    //- Route::resource('commentpub', 'CommentPubController');
	    // Commentaire des interviews
	    //- Route::resource('commentint', 'CommentIntController');
    });
});


Route::middleware('auth')->group(function () {
	Route::group(['prefix' => 'admin'], function () {
	    // Commentaire des publications
	    Route::resource('commentpub', 'CommentPubController');
	    // Commentaire des interviews
	    Route::resource('commentint', 'CommentIntController');
    });
});

app/Models/Auteur.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Auteur extends Model
{
    protected $fillable = ['nom', 'prenom', 'contact', 'email', 'filiere', 'fonction'];

    public function Publication()
    {
       return $this->hasMany('App\Models\Publication');
    }

    public function Interview()
    {
        return $this->hasMany('App\Models\Interview');
    }
}

app/Http/Controllers/AuteurController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Auteur;

class AuteurController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    // public function __construct()
    // {
    //     $this->middleware('auth');
    // }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $Auteur = Auteur::OrderBy('id','desc')->get();
        return view('administration.Auteur.index',compact('Auteur'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('administration.Auteur.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request,[
           'nom'=>'Required',
           'prenom'=>'Required',
           'contact'=>'Required',
           'email'=>'Required',
           'filiere'=>'Required',
           'fonction'=>'Required',
        ]);

        Auteur::create([
        'nom'=>$request->nom,
        'prenom'=>$request->prenom,
        'contact'=>$request->contact,
        'email'=>$request->email,
        'filiere'=>$request->filiere,
        'fonction'=>$request->fonction
        ]);
        Session()->flash("create", "L'auteur à bien été ajouté avec success !"); 
        return redirect()->route('auteurs.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $Auteur = Auteur::findOrFail($id);
        return view('administration.Auteur.show', compact('Auteur'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $Auteur = Auteur::findOrFail($id);
        return view('administration.Auteur.edit', compact('Auteur'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request,[
           'nom'=>'Required',
           'prenom'=>'Required',
           'contact'=>'Required',
           'email'=>'Required',
           'filiere'=>'Required',
           'fonction'=>'Required',
        ]);

        $Auteur = Auteur::findOrFail($id);
        $Auteur->update([
            'nom'=>$request->nom,
            'prenom'=>$request->prenom,
            'contact'=>$request->contact,
            'email'=>$request->email,
            'filiere'=>$request->filiere,
            'fonction'=>$request->fonction
        ]);
        Session()->flash("update", "L'auteur à bien été mis à jour avec success !");    
        return redirect()->route('auteurs.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Auteur::destroy($id);
        Session()->flash("message", "L'auteur à bien été supprimé avec success !");  
        return redirect()->route('auteurs.index');
    }
}

resources/views/administration/Auteur/create.blade.php
@extends('layouts.sidebar-profil') @section('content')



    <!--maincontent-->
        <div class="mainWrap navslide">
            <div class="ui equal width left aligned padded grid stackable">
                <!--Site Content-->
                <!--Site Content-->
            
                        <div class="row">
                            <div class="ten wide column">
                            			<div class="ui segments">
                                    <div class="ui segment">
                                        <h5 class="ui header">
                                            Ajouter un auteur
                                        </h5>
                                        <a href="{{route('auteurs.index')}}">
                                            <button class="ui lightbrownli  button">Voir la liste</button>
                                        </a>
                                    </div>
                                    <form class="ui form segment form3" action="{{route('auteurs.store')}}" method="POST">
                                    	{{csrf_field()}}
				  							 @csrf
                                        <div class="two fields">
                                            <div class="field">
                                                <label>Nom</label>
                                                <input placeholder="nom" name="nom" type="text">
                                                @error('nom')
                                                <div class="ui redli message">
                                                    <i class="close icon"></i>
                                                    <div class="header">
                                                        Veuillez renseinger ce champs
                                                    </div>
                                                </div>
                                                @enderror
                                               
                                            </div>
                                             <div class="field">
                                                <label>Prenom</label>
                                                <input placeholder="prenom" name="prenom" type="text">
                                                @error('prenom')
                                                <div class="ui redli message">
                                                    <i class="close icon"></i>
                                                    <div class="header">
                                                        Veuillez renseinger ce champs
                                                    </div>
                                                </div>
                                                @enderror
                                            </div>
                                        </div>
                                        <div class="two fields">
                                            <div class="field">
                                                <label>Contact</label>
                                                <input placeholder="contact" name="contact" type="number">
                                                @error('contact')
                                                <div class="ui redli message">
                                                    <i class="close icon"></i>
                                                    <div class="header">
                                                        Veuillez renseinger ce champs
                                                    </div>
                                                </div>
                                                @enderror
                                            </div>
                                             <div class="field">
                                                <label>Filiere</label>
                                                <input placeholder="filiere" name="filiere" type="text">
                                                @error('filiere')
                                                <div class="ui redli message">
                                                    <i class="close icon"></i>
                                                    <div class="header">
                                                        Veuillez renseinger ce champs
                                                    </div>
                                                </div>
                                                @enderror
                                            </div>
                                        </div>
                                        <div class="two fields">
                                            <div class="field">
                                                <label>Fonction</label>
                                                <input placeholder="fonction" name="fonction" type="text">
                                                @error('fonction')
                                                <div class="ui redli message">
                                                    <i class="close icon"></i>
                                                    <div class="header">
                                                        Veuillez renseinger ce champs
                                                    </div>
                                                </div>
                                                @enderror
                                            </div>
                                             <div class="field">
                                                <label>date de création</label>
                                                <input value="{{date('d-m-Y', strtotime(NOW()))}}" type="text" disabled readonly>
                                            </div>
                                        </div>
                                        <div class="field">
                                            <label>Adresse Mail</label>
                                            <input name="email" placeholder="Adresse Mail" type="email">
                                            @error('email')
                                                <div class="ui redli message">
                                                    <i class="close icon"></i>
                                                    <div class="header">
                                                        Veuillez renseinger ce champs
                                                    </div>
                                                </div>
                                            @enderror
                                        </div>
                                        <button type="submit" class="ui blue submit button">Enregistrer</button>
                                    </form>
                                </div>
                            </div>
                        </div>
            </div>
        </div>



@endsection

resources/views/administration/Auteur/edit.blade.php
@extends('layouts.sidebar-profil') @section('content')



    <!--maincontent-->
        <div class="mainWrap navslide">
            <div class="ui equal width left aligned padded grid stackable">
                <!--Site Content-->
                <!--Site Content-->
            
                        <div class="row">
                            <div class="ten wide column">
                            			<div class="ui segments">
                                    <div class="ui segment">
                                        <h5 class="ui header">
                                            Ajouter un auteur
                                        </h5>
                                    </div>
                                    <form class="ui form segment form3" action="{{route('auteurs.update', $Auteur)}}" method="POST">
                                    	{{csrf_field()}}
                            			{{method_field('PUT')}}
                                        <div class="two fields">
                                            <div class="field">
                                                <label>Nom</label>
                                                <input value="{{$Auteur->nom}}" name="nom" type="text" required>
                                            </div>
                                             <div class="field">
                                                <label>Prenom</label>
                                                <input value="{{$Auteur->prenom}}" name="prenom" type="text" required>
                                            </div>
                                        </div>
                                        <div class="two fields">
                                            <div class="field">
                                                <label>Contact</label>
                                                <input value="{{$Auteur->contact}}" name="contact" type="number" required>
                                            </div>
                                             <div class="field">
                                                <label>Filiere</label>
                                                <input value="{{$Auteur->filiere}}" name="filiere" type="text" required>
                                            </div>
                                        </div>
                                        <div class="two fields">
                                            <div class="field">
                                                <label>Fonction</label>
                                                <input value="{{$Auteur->fonction}}" name="fonction" type="text" required>
                                            </div>
                                             <div class="field">
                                                <label>date de création</label>
                                                <input value="{{date('d-m-Y', strtotime(NOW()))}}" type="text" disabled readonly>
                                            </div>
                                        </div>
                                        <div class="field">
                                            <label>Adresse Mail</label>
                                            <input name="email" value="{{$Auteur->email}}" type="email" required>
                                        </div>
                                        <button type="submit" class="ui blue submit button">Mettre à Jour</button>
                                    </form>
                                </div>
                            </div>
                        </div>
            </div>
        </div>



@endsection

resources/views/administration/Auteur/index.blade.php
@extends('layouts.sidebar-profil') @section('content')

<br>


    <!--maincontent-->
        <div class="mainWrap navslide">
            <div class="ui equal width left aligned padded grid stackable">
                <!--Site Content-->
                <!--Site Content-->
            
                        <div class="row">
                            <div class="sixteen wide column">
                                <div class="ui segments">
                                    <div class="ui segment">
                                        <h5 class="ui header">
                                            Liste des Auteurs 
                                        </h5>
                                        <a href="{{route('auteurs.create')}}">
                                            <button class="ui blueli button">Ajouter</button>
                                        </a>
                                        @if(session()->has('message'))
                                            <div class="ui icon message inverted redli">
                                                <i class="alarm icon"></i>
                                                <div class="content">
                                                    <div class="header">
                                                        {{ session()->get('message') }}
                                                    </div>
                                                    <!-- <p>{{ session()->get('message') }}</p> -->
                                                </div>
                                            </div>
                                        @endif
                                        @if(session()->has('create'))
                                            <div class="ui icon message inverted greenli">
                                                <i class="alarm icon"></i>
                                                <div class="content">
                                                    <div class="header">
                                                        {{ session()->get('create') }}
                                                    </div>
                                                    <!-- <p>{{ session()->get('message') }}</p> -->
                                                </div>
                                            </div>
                                        @endif
                                        @if(session()->has('update'))
                                            <div class="ui icon message inverted orange">
                                                <i class="alarm icon"></i>
                                                <div class="content">
                                                    <div class="header">
                                                        {{ session()->get('update') }}
                                                    </div>
                                                    <!-- <p>{{ session()->get('message') }}</p> -->
                                                </div>
                                            </div>
                                        @endif

                                    </div>
                                    <div class="ui segment">
                                        <table id="data_table" class="ui compact selectable striped celled table tablet stackable" cellspacing="0" width="100%">
                                            <thead>
                                                <tr>
                                                    <th>Nom & Prenom</th>
                                                    <th>Contact</th>
                                                    <th>Addresse Mail</th>
                                                    <th>Filière</th>
                                                    <th>Fonction</th>
                                                    <th>Modifier</th>
                                                    <th>Supprimer</th>
                                                </tr>
                                            </thead>

                                            <tbody>
                                                @foreach($Auteur as $redacteur)
                                                <tr>
                                                    <td>{{$redacteur->nom}} {{$redacteur->prenom}}</td>
                                                    <td>
                                                        {{$redacteur->contact}}
                                                    </td>
                                                    <td>
                                                        {{$redacteur->email}}
                                                    
                                                    </td>
                                                    <td>{{$redacteur->filiere}}</td>
                                                    <td>{{$redacteur->fonction}}</td>
                                                    <td>
                                                        <a href="{{route('auteurs.edit', $redacteur)}}">
                                                            <button class="ui orange button">
                                                                <i class="pencil icon ui dark"></i>
                                                            </button>
                                                        </a>
                                                    </td>
                                                    <td>
                                                        <form action = "{{ route('auteurs.destroy',$redacteur) }}"
                                                            method = "POST"
                                                            onsubmit = "return confirm('Êtes vous sûre ?')"; >
                                                            {{ csrf_field() }}
                                                            {{ method_field('DELETE') }}
                                                            <button class="ui red button" type="submit">
                                                                <i class="close icon ui dark"></i>
                                                            </button>
                                                        </form>
                                                    </td>
                                                </tr>
                                                @endforeach
                                                
                                            </tbody>
                                        </table>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
        </div>
        <!--maincontent-->



@endsection

resources/views/administration/Auteur/show.blade.php
@extends('layouts.sidebar-profil') @section('content')



    <!--maincontent-->
        <div class="mainWrap navslide">
            <div class="ui equal width left aligned padded grid stackable">
                <!--Site Content-->
                <!--Site Content-->
            
                        <div class="row">
                            <div class="sixteen wide column">
                            			
                            </div>
                        </div>
            </div>
        </div>



@endsection