routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });

// Route d'authentification
Auth::routes();

// Page de Profil de l'utilisateur
Route::get('/home', 'HomeController@index')->name('home');

// Page d'acceuil
Route::get('/', 'internauteController@accueil')->name('accueil');

// Publications
Route::get('/article/{id}/detail', 'internauteController@view_article')->name('view_article');
Route::get('/articles', 'internauteController@list_articles')->name('list_articles');

// Interviews
Route::get('/interview/{id}/detail', 'internauteController@view_interview')->name('view_interview');
Route::get('/interview', 'internauteController@list_interview')->name('list_interview');

// Search
Route::get('/search', 'internauteController@search')->name('search');

// Contact
Route::get('/contact', 'internauteController@contact')->name('contact');

// Route dédiée au administrateurs connu sous le nom de membre (@membre @endmembre)

Route::middleware('membre')->group(function () {
	Route::group(['prefix' => 'admin'], function () {
	    Route::resource ('interviews', 'InterviewController', [
	        //'except' => 'show'
	    ]);
	    Route::resource('publications', 'publicationController');
	    Route::resource('flash', 'FlashController');
	    Route::resource('auteurs', 'AuteurController');
	    Route::resource('news', 'newsletterController');
	    // Envoie de mail à plusieurs
		Route::post('/all', 'newsletterController@all')->name('all');
		// Liste des messages envoyés au abonnés
		Route::get('/list_messages', 'newsletterController@list_messages')->name('list_messages');
	    // Contactez l'équipe
	    Route::resource('contact', 'ContactController');
	    // Commentaire des publications
	    //- Route::resource('commentpub', 'CommentPubController');
	    // Commentaire des interviews
	    //- Route::resource('commentint', 'CommentIntController');
    });
});


Route::middleware('auth')->group(function () {
	Route::group(['prefix' => 'admin'], function () {
	    // Commentaire des publications
	    Route::resource('commentpub', 'CommentPubController');
	    // Commentaire des interviews
	    Route::resource('commentint', 'CommentIntController');
    });
});

app/Models/Publication.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Publication extends Model
{
    protected $fillable = ['libelle', 'image', 'contenu', 'type_publication_id', 'auteur_id'];

    public function typePublication()
    {
        return $this->belongsTo('App\Models\typePublication');
    }

    public function Auteur()
    {
        return $this->belongsTo('App\Models\Auteur');
    }

    public function Commentpublication()
    {
       return $this->hasMany('App\Models\Commentpublication');
    }
}

app/Http/Controllers/publicationController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Models\typePublication;
use App\Models\Publication;
use App\Models\Auteur;

class publicationController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $Publication = Publication::with('typePublication','Auteur')->OrderBy('id','desc')->get();
        // dd($Publication);
        return view('administration.Publication.index',compact('Publication'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $typePublication = typePublication::OrderBy('id','desc')->get();
        $Auteur = Auteur::OrderBy('id','desc')->get();
        $publication_filtrer = $typePublication;  
        return view('administration.Publication.create',compact('typePublication', 'Auteur', 'publication_filtrer'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request,[
           'libelle'=>'Required',
           'type_publication_id'=>'Required',
           'auteur_id'=>'Required',
           'contenu'=>'Required'
        ]);

        if($request->type_publication_id == 7 && $request->image == null || $request->image == null) // Anglais
        {
            $inputArray = [
                '0.jpg',
                '1.jpg',
                '2.jpg'
            ];
            $randomItems = array_rand($inputArray);
            $nomAvatar = $randomItems.'.jpg';
        }else{
            $image = $request->file('image');
            // Obtenir l'extension
            // dd($image );
            $nomAvatar = time().'.'.$image->getClientOriginalExtension();
            // time() génère un nom aléatoire
            $image->move(public_path("image_publication"), $nomAvatar );
            // $image->move(base_path("image_publication"), $nomAvatar );
        }  

        Publication::create([
        'libelle'=>$request->libelle,
        'type_publication_id'=>$request->type_publication_id,
        'auteur_id'=>$request->auteur_id,
        'image'=>$nomAvatar,
        'contenu'=>$request->contenu,
        'flashinfo'=>$request->flashinfo
        ]);
        Session()->flash('create', 'La Publication à été Ajouté avec success !'); 
        return redirect()->route('publications.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $Publication=Publication::findOrFail($id);
        return view('administration.Publication.show',compact('Publication'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $typePublication = typePublication::OrderBy('id','desc')->get();
        $Auteur = Auteur::OrderBy('id','desc')->get();
        $collection = collect($typePublication);
        // Retrieve all items from the collect
        $publication_filtrer = $collection->except([0,2]); // Except Flash Info & Anglais
        $Publication=Publication::with('typePublication','Auteur')->findOrFail($id);
        // dd($Publication);
        return view('administration.Publication.edit',compact('Publication', 'publication_filtrer', 'Auteur'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request,[
           'libelle'=>'Required',
           'type_publication_id'=>'Required',
           'auteur_id'=>'Required',
           'contenu'=>'Required'
        ]);

        if($request->type_publication_id == 7 && $request->image == null || $request->image == null) // Anglais
        {
            $inputArray = [
                '0.jpg',
                '1.jpg',
                '2.jpg'
            ];
            $randomItems = array_rand($inputArray);
            $nomAvatar = $randomItems.'.jpg';
            $Publication=Publication::findOrFail($id);
            // dd($Publication->image);die(); // Vérification de l'image
            $nomAvatar = $Publication->image;
        }else{
            $image = $request->file('image');
            // Obtenir l'extension
            // dd($image );
            $nomAvatar = time().'.'.$image->getClientOriginalExtension();
            // time() génère un nom aléatoire_ç
            $image->move(public_path("image_publication"), $nomAvatar );
            // $image->move(base_path("image_publication"), $nomAvatar );
        } 

            $Publication=Publication::findOrFail($id);
            // dd($request->libelle);
            $Publication->update([
                'libelle'=>$request->libelle,
                'contenu'=>$request->contenu,
                'image'=>$nomAvatar,
                'type_publication_id'=>$request->type_publication_id,
                'auteur_id'=>$request->auteur_id,
            ]);
 
        
        Session()->flash('update', 'La Publication à été mise à jour avec success !'); 
        return redirect()->route('publications.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Publication::destroy($id);
        Session()->flash("delete", "L'article à bien été supprimé avec success !");  
        return redirect()->route('publications.index');
    }
}

resources/views/administration/Publication/create.blade.php
@extends('layouts.sidebar-profil') @section('content')



    <!--maincontent-->
        <div class="mainWrap navslide">
            <div class="ui equal width left aligned padded grid stackable">
                <!--Site Content-->
                <!--Site Content-->
            
                        <div class="row">
                            <div class="ten wide column">
                            	<div class="ui segments">
                                    <div class="ui segment">
                                        <h5 class="ui header">
                                            Ajouter un article
                                        </h5>
                                        <a href="{{route('publications.index')}}">
                                            <button class="ui lightbrownli  button">Voir la liste</button>
                                        </a>
                                    </div>
                                    <form class="ui form segment form3" enctype="multipart/form-data" action="{{route('publications.store')}}" method="POST">
                                    	{{csrf_field()}}
				  							 @csrf
                                        <div class="two fields">
                                            <div class="field">
                                                <label>Titre de l'article</label>
                                                <input placeholder="Titre de l'article" name="libelle" type="text">
                                               @error('libelle')
                                                <div class="ui redli message">
                                                    <i class="close icon"></i>
                                                    <div class="header">
                                                        Veuillez renseinger ce champs
                                                    </div>
                                                </div>
                                                @enderror
                                            </div>
                                             <div class="field">
                                                <label>Categories</label>
                                                <div class="ui dropdown selection" tabindex="0">
                                                    <select name="type_publication_id">
                                                    	@foreach($publication_filtrer as $pub)
                                                        <option value="">Categories</option>
                                                        <option value="{{$pub->id}}">{{$pub->libelle}}</option>
                                                        @endforeach
                                                    </select><i class="dropdown icon"></i>
                                                    <div class="default text">Categories</div>
                                                    <div class="menu" tabindex="-1">
                                                    	@foreach($publication_filtrer as $pub)
                                                    		<div class="item" data-value="{{$pub->id}}">{{$pub->libelle}}</div>
                                                    	@endforeach
                                                    </div>
                                                </div>
                                                @error('type_publication_id')
                                                <div class="ui redli message">
                                                    <i class="close icon"></i>
                                                    <div class="header">
                                                        Veuillez renseinger ce champs
                                                    </div>
                                                </div>
                                                @enderror
                                            </div>
                                        </div>
                                        <div class="two fields">
                                            <div class="field">
                                                <label>Auteur</label>
                                                <div class="ui dropdown selection" tabindex="0">
                                                    <select name="auteur_id">
                                                    	@foreach($Auteur as $pub)
                                                        <option value="">Auteur</option>
                                                        <option value="{{$pub->id}}">{{$pub->nom}} {{$pub->prenom}}</option>
                                                        @endforeach
                                                    </select><i class="dropdown icon"></i>
                                                    <div class="default text">Auteur</div>
                                                    <div class="menu" tabindex="-1">
                                                    	@foreach($Auteur as $pub)
                                                    		<div class="item" data-value="{{$pub->id}}">{{$pub->nom}} {{$pub->prenom}}</div>
                                                    	@endforeach
                                                    </div>
                                                </div>
                                                @error('auteur_id')
                                                <div class="ui redli message">
                                                    <i class="close icon"></i>
                                                    <div class="header">
                                                        Veuillez renseinger ce champs
                                                    </div>
                                                </div>
                                                @enderror
                                            </div>
                                             <div class="field">
                                                <label>image</label>
                                                <input placeholder="image" name="image" type="file">
                                                @error('image')
                                                <div class="ui redli message">
                                                    <i class="close icon"></i>
                                                    <div class="header">
                                                        Veuillez renseinger ce champs
                                                    </div>
                                                </div>
                                                @enderror
                                            </div>
                                        </div>
                                      
                                        <div class="field">
                                            <label>contenu</label>
                                            <div class="field">
                                                <textarea class="trumbowygeditor" name="contenu"></textarea>
                                            </div>
                                        <button type="submit" class="ui blue submit button">Enregistrer</button>
                                    </form>
                                </div>
                            </div>
                            
                        </div>
            </div>
        </div>



@endsection

resources/views/administration/Publication/index.blade.php
@extends('layouts.sidebar-profil') @section('content')

<br>


    <!--maincontent-->
        <div class="mainWrap navslide">
            <div class="ui equal width left aligned padded grid stackable">
                <!--Site Content-->
                <!--Site Content-->
            
                        <div class="row">
                            <div class="sixteen wide column">
                                <div class="ui segments">
                                    <div class="ui segment">
                                        <h5 class="ui header">
                                            Liste des articles 
                                        </h5>
                                        <a href="{{route('publications.create')}}">
                                            <button class="ui lightbrownli  button">Ajouter un nouvel article</button>
                                        </a>
                                        @if(session()->has('create'))
                                            <div class="ui icon message inverted greenli">
                                                <i class="alarm icon"></i>
                                                <div class="content">
                                                    <div class="header">
                                                        {{ session()->get('create') }}
                                                    </div>
                                                    <!-- <p>{{ session()->get('message') }}</p> -->
                                                </div>
                                            </div>
                                        @endif  

                                        @if(session()->has('delete'))
                                            <div class="ui icon message inverted redli">
                                                <i class="alarm icon"></i>
                                                <div class="content">
                                                    <div class="header">
                                                        {{ session()->get('delete') }}
                                                    </div>
                                                    <!-- <p>{{ session()->get('delete') }}</p> -->
                                                </div>
                                            </div>
                                        @endif 

                                        @if(session()->has('update'))
                                            <div class="ui icon message inverted greenli">
                                                <i class="alarm icon"></i>
                                                <div class="content">
                                                    <div class="header">
                                                        {{ session()->get('update') }}
                                                    </div>
                                                    <!-- <p>{{ session()->get('message') }}</p> -->
                                                </div>
                                            </div>
                                        @endif

                                    </div>
                                    <div class="ui segment">
                                        <table id="data_table" class="ui compact selectable striped celled table tablet stackable" cellspacing="0" width="100%">
                                            <thead>
                                                <tr>
                                                    <th>Libelle de l'article</th>
                                                    <th>Date de publication</th>
                                                    <th>Description</th>
                                                    <th>Type d'article</th>
                                                    <th>Auteur</th>
                                                    <th>Modifier</th>
                                                    <th>Supprimer</th>
                                                </tr>
                                            </thead>

                                            <tbody>
                                                @foreach($Publication as $Pub)
                                                <tr>
                                                    <td>{{$Pub->libelle}}</td>
                                                    <td>
                                                        {{date('d-m-Y', strtotime($Pub->created_at)) }}
                                                    </td>
                                                    <td>
                                                        <!-- <img class="ui small image" src="../../image_publication/{{$Pub->image}}" alt=""> -->
                                                        <!-- {{$Pub->contenu}} -->
                                                        <!-- {!! Str::limit($Pub->contenu, 50, ' ...') !!} -->
                                                        <!-- <br> -->
                                                        <a href="{{route('publications.show', $Pub->id)}}">
                                                            <button class="ui blueli  button">aperçu de l'article</button>
                                                        </a>
                                                    
                                                       <br> 
                                                    </td>
                                                    <td>{{$Pub->typePublication->libelle}}</td>
                                                    <td>{{$Pub->Auteur->nom}} {{$Pub->Auteur->prenom}}</td>
                                                    <td> 
                                                        <a href="{{route('publications.edit',$Pub->id)}}">
                                                            <button class="ui brown button">
                                                                <i class="pencil alternate icon ui dark"></i>
                                                            </button>
                                                        </a>
                                                    </td>
                                                    <td>
                                                        <form action = "{{ route('publications.destroy',$Pub) }}"
                                                            method = "POST"
                                                            onsubmit = "return confirm('Êtes vous sûre ?')"; >
                                                            {{ csrf_field() }}
                                                            {{ method_field('DELETE') }}
                                                            <button class="ui red button" type="submit">
                                                                <i class="close icon ui dark"></i>
                                                            </button>
                                                        </form>
                                                    </td>
                                                </tr>
                                                @endforeach
                                                
                                            </tbody>
                                        </table>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
        </div>
        <!--maincontent-->



@endsection

resources/views/administration/Publication/show.blade.php
@extends('layouts.sidebar-profil') @section('content')



    <!--maincontent-->
        <div class="mainWrap navslide">
            <div class="ui equal width left aligned padded grid stackable">
                <!--Site Content-->
                <!--Site Content-->
            
                        <div class="row">
                            <div class="sixteen wide column">
                                <br>
                                <a href="{{route('publications.index')}}">
                                    <button class="ui lightbrownli  button">Voir la liste</button>
                                </a>
                                <br>
                                @if($Publication->type_publication_id == 7)
                            	<img class="ui small image" src="../../Ang640x480/{{$Publication->image}}" alt="">
                                @else
                                <img class="ui small image" src="../../image_publication/{{$Publication->image}}" alt="">
                                @endif
                                        {!! $Publication->contenu !!}	
                            </div>
                        </div>
            </div>
        </div>



@endsection